<a href="https://colab.research.google.com/github/KhandareAshutosh/IPL_Prediction_ML_Project/blob/main/WIDs_IPL_Score_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Wids_IPL_Analysis_Data/0y clean data pre ipl.csv')

In [ ]:
listf = []
for c in dataset.columns:
    if dataset[c].dtype==object:
        print(c,"->" ,dataset[c].dtype)
        listf.append(c)

venue -> object
batting_team -> object
bowling_team -> object
striker -> object
non_striker -> object
bowler -> object
wicket_type -> object
player_dismissed -> object

In [ ]:
dataset.head(2)

,Unnamed: 0,match_id,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wicket_type,player_dismissed,run,wickets,truns,y
0,0,335982,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0.0,1.0,,,1.0,0.0,1.0,68.0
1,1,335982,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0.0,0.0,,,0.0,0.0,1.0,68.0

In [ ]:
dataset= dataset.drop(['Unnamed: 0','extras','match_id', 'runs_off_bat'],axis = 1)
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32178 entries, 0 to 32177
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   venue             32178 non-null  object
 1   innings           32178 non-null  int64
 2   ball              32178 non-null  float64
 3   batting_team      32178 non-null  object
 4   bowling_team      32178 non-null  object
 5   striker           32178 non-null  object
 6   non_striker       32178 non-null  object
 7   bowler            32178 non-null  object
 8   wicket_type       32178 non-null  object
 9   player_dismissed  32178 non-null  object
 10  run               32178 non-null  float64
 11  wickets           32178 non-null  float64
 12  truns             32178 non-null  float64
 13  y                 32178 non-null  float64
dtypes: float64(5), int64(1), object(8)
memory usage: 3.4+ MB

In [ ]:
a1 = dataset['venue'].unique()
a2 = dataset['batting_team'].unique()
a3 = dataset['bowling_team'].unique()
a4 = dataset['striker'].unique()
a5 = dataset['bowler'].unique()

In [ ]:
def labelEncoding(data):
    dataset = pd.DataFrame(data)
    feature_dict ={}
    #features={}
    for feature in dataset:
        if dataset[feature].dtype==object:
            le = preprocessing.LabelEncoder()
            fs = dataset[feature].unique()
            le.fit(fs)
            dataset[feature] = le.transform(dataset[feature])
            feature_dict[feature] = le
            print(feature)
    return dataset

labelEncoding(dataset)

venue
batting_team
bowling_team
striker
non_striker
bowler
wicket_type
player_dismissed

,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,wicket_type,player_dismissed,run,wickets,truns,y
0,15,1,0.1,7,13,186,30,201,0,0,1.0,0.0,1.0,68.0
1,15,1,0.2,7,13,30,184,201,0,0,0.0,0.0,1.0,68.0
2,15,1,0.3,7,13,30,184,201,0,0,1.0,0.0,2.0,68.0
3,15,1,0.4,7,13,30,184,201,0,0,0.0,0.0,2.0,68.0
4,15,1,0.5,7,13,30,184,201,0,0,0.0,0.0,2.0,68.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32173,31,1,6.2,14,10,48,126,220,0,0,1.0,1.0,53.0,57.0
32174,31,1,6.3,14,10,127,47,220,0,0,1.0,1.0,54.0,57.0
32175,31,1,6.4,14,10,48,126,220,0,0,1.0,1.0,55.0,57.0
32176,31,1,6.5,14,10,127,47,220,0,0,1.0,1.0,56.0,57.0
32177,31,1,6.6,14,10,48,126,220,0,0,1.0,1.0,57.0,57.0

In [ ]:
ip_dataset = dataset[['venue','innings', 'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler']]
b1 = ip_dataset['venue'].unique()
b2 = ip_dataset['batting_team'].unique()
b3 = ip_dataset['bowling_team'].unique()
b4 = ip_dataset['striker'].unique()
b5 = ip_dataset['bowler'].unique()
#ip_dataset.head(2)

In [ ]:
features={}
for i in range(len(a1)):
    features[a1[i]]=b1[i]
for i in range(len(a2)):
    features[a2[i]]=b2[i]
for i in range(len(a3)):
    features[a3[i]]=b3[i]
for i in range(len(a4)):
    features[a4[i]]=b4[i]
for i in range(len(a5)):
    features[a5[i]]=b5[i]
features

{'M Chinnaswamy Stadium': 15,
 'Punjab Cricket Association Stadium, Mohali': 26,
 'Feroz Shah Kotla': 9,
 'Eden Gardens': 8,
 'Wankhede Stadium': 39,
 'Sawai Mansingh Stadium': 31,
 'Rajiv Gandhi International Stadium, Uppal': 28,
 'MA Chidambaram Stadium, Chepauk': 18,
 'Dr DY Patil Sports Academy': 5,
 'Newlands': 22,
 "St George's Park": 35,
 'Kingsmead': 14,
 'SuperSport Park': 37,
 'Buffalo Park': 3,
 'New Wanderers Stadium': 21,
 'De Beers Diamond Oval': 4,
 'OUTsurance Oval': 23,
 'Brabourne Stadium': 2,
 'Sardar Patel Stadium, Motera': 29,
 'Barabati Stadium': 1,
 'Vidarbha Cricket Association Stadium, Jamtha': 38,
 'Himachal Pradesh Cricket Association Stadium': 11,
 'Nehru Stadium': 20,
 'Holkar Cricket Stadium': 12,
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium': 6,
 'Subrata Roy Sahara Stadium': 36,
 'Shaheed Veer Narayan Singh International Stadium': 32,
 'JSCA International Stadium Complex': 13,
 'Sheikh Zayed Stadium': 34,
 'Sharjah Cricket Stadium': 33,
 'Dubai International Cricket Stadium': 7,
 'Maharashtra Cricket Association Stadium': 19,
 'Punjab Cricket Association IS Bindra Stadium, Mohali': 25,
 'Saurashtra Cricket Association Stadium': 30,
 'Green Park': 10,
 'M.Chinnaswamy Stadium': 16,
 'MA Chidambaram Stadium': 17,
 'Arun Jaitley Stadium': 0,
 'Rajiv Gandhi International Stadium': 27,
 'Punjab Cricket Association IS Bindra Stadium': 24,
 'Kolkata Knight Riders': 7,
 'Chennai Super Kings': 0,
 'Rajasthan Royals': 10,
 'Deccan Chargers': 1,
 'Mumbai Indians': 8,
 'Kings XI Punjab': 5,
 'Royal Challengers Bangalore': 13,
 'Delhi Daredevils': 3,
 'Kochi Tuskers Kerala': 6,
 'Pune Warriors': 9,
 'Sunrisers Hyderabad': 14,
 'Rising Pune Supergiants': 12,
 'Gujarat Lions': 4,
 'Rising Pune Supergiant': 11,
 'Delhi Capitals': 2,
 'SC Ganguly': 259,
 'BB McCullum': 30,
 'RT Ponting': 174,
 'PA Patel': 150,
 'ML Hayden': 129,
 'MEK Hussey': 123,
 'MS Dhoni': 135,
 'T Kohli': 213,
 'YK Pathan': 314,
 'SR Watson': 275,
 'M Kaif': 113,
 'AC Gilchrist': 9,
 'Y Venugopal Rao': 312,
 'VVS Laxman': 224,
 'A Symonds': 8,
 'L Ronchi': 108,
 'ST Jayasuriya': 203,
 'DJ Thornely': 56,
 'RV Uthappa': 175,
 'PR Shah': 156,
 'K Goel': 131,
 'JR Hopes': 127,
 'KC Sangakkara': 98,
 'DPMD Jayawardene': 59,
 'SK Raina': 264,
 'Shahid Afridi': 281,
 'IK Pathan': 102,
 'WP Saha': 228,
 'DJ Hussey': 73,
 'S Chanderpaul': 178,
 'R Dravid': 160,
 'LRPL Taylor': 112,
 'JH Kallis': 119,
 'V Kohli': 300,
 'AM Rahane': 18,
 'SM Pollock': 271,
 'G Gambhir': 68,
 'V Sehwag': 302,
 'S Dhawan': 243,
 'Shoaib Malik': 210,
 'MK Tiwary': 128,
 'DB Das': 49,
 'GC Smith': 69,
 'SA Asnodkar': 183,
 'HH Gibbs': 74,
 'SP Fleming': 194,
 'S Vidyut': 182,
 'SE Marsh': 188,
 'Yuvraj Singh': 316,
 'B Chipli': 28,
 'W Jaffer': 226,
 'S Badrinath': 177,
 'YV Takawale': 232,
 'CL White': 45,
 'S Anirudha': 176,
 'AB de Villiers': 7,
 'A Chopra': 0,
 'BJ Hodge': 51,
 'Salman Butt': 207,
 'J Arunkumar': 81,
 'Misbah-ul-Haq': 139,
 'Mohammad Hafeez': 186,
 'SR Tendulkar': 199,
 'SP Goswami': 195,
 'LA Pomersbach': 109,
 'SB Styris': 257,
 'MV Boucher': 137,
 'JD Ryder': 113,
 'KP Pietersen': 147,
 'RS Bopara': 236,
 'CH Gayle': 56,
 'TM Dilshan': 296,
 'PC Valthaty': 152,
 'RJ Quiney': 169,
 'DR Smith': 82,
 'KD Karthik': 99,
 'AA Bilakhia': 4,
 'RG Sharma': 229,
 'Harbhajan Singh': 98,
 'AM Nayar': 27,
 'R Bishnoi': 159,
 'M Vijay': 168,
 'JP Duminy': 125,
 'DJ Bravo': 70,
 'NV Ojha': 146,
 'MN van Wyk': 132,
 'TL Suman': 295,
 'Yashpal Singh': 233,
 'S Sohal': 181,
 'SM Katich': 191,
 'AN Ghosh': 19,
 'DA Warner': 48,
 'GJ Bailey': 71,
 'M Manhas': 115,
 'Niraj Patel': 147,
 'J Botha': 106,
 'MK Pandey': 127,
 'RE van der Merwe': 227,
 'Mohammad Ashraful': 140,
 'CA Pujara': 41,
 'OA Shah': 148,
 'AD Mathews': 20,
 'MS Bisla': 134,
 'AP Tare': 21,
 'SS Tiwary': 202,
 'AT Rayudu': 24,
 'EJG Morgan': 64,
 'AA Jhunjhunwala': 12,
 'MJ Lumb': 126,
 'DR Martyn': 60,
 'FY Fazal': 67,
 'MD Mishra': 121,
 'Mandeep Singh': 138,
 'PD Collingwood': 153,
 'KM Jadhav': 104,
 'C Madan': 36,
 'AG Paunikar': 14,
 'R McLaren': 218,
 'Anirudh Singh': 25,
 'IR Jaggi': 79,
 'Sunny Singh': 212,
 'UBT Chand': 218,
 'AJ Finch': 24,
 'MA Agarwal': 118,
 'RA Jadeja': 226,
 'AL Menaria': 26,
 'DJ Jacobs': 55,
 'AS Raut': 23,
 'TD Paine': 214,
 'BJ Haddin': 33,
 'R Sathish': 162,
 'MS Wade': 136,
 'Y Nagar': 311,
 'AC Blizzard': 8,
 'M Klinger': 114,
 'DB Ravi Teja': 50,
 'CJ Ferguson': 44,
 'CA Ingram': 39,
 'RN ten Doeschate': 170,
 'F du Plessis': 66,
 'LR Shukla': 160,
 'R Bhatia': 216,
 'WD Parnell': 308,
 'AB McDonald': 16,
 'MN Samuels': 181,
 'DT Christian': 84,
 'RE Levi': 166,
 'N Saini': 143,
 'JEC Franklin': 118,
 'DJ Harris': 71,
 'MJ Clarke': 175,
 'AP Majumdar': 20,
 'STR Binny': 278,
 'SD Chitnis': 261,
 'Azhar Mahmood': 38,
 'PA Reddy': 151,
 'MC Juneja': 120,
 'MDKJ Perera': 122,
 'KK Nair': 102,
 'M Vohra': 117,
 'Gurkeerat Singh': 94,
 'Q de Kock': 157,
 'GH Vihari': 90,
 'BB Samantray': 31,
 'KV Sharma': 149,
 'A Mishra': 4,
 'NLTC Perera': 196,
 'DJG Sammy': 76,
 'A Mukund': 2,
 'JP Faulkner': 126,
 'SV Samson': 205,
 'CM Gautam': 46,
 'MC Henriques': 171,
 'GJ Maxwell': 91,
 'CA Lynn': 40,
 'CJ Anderson': 58,
 'S Rana': 180,
 'JA Morkel': 111,
 'KL Rahul': 103,
 'BR Dunk': 35,
 'DA Miller': 47,
 'LMP Simmons': 110,
 'VH Zol': 223,
 'Ankit Sharma': 35,
 'KK Cooper': 143,
 'RR Rossouw': 172,
 'SS Iyer': 201,
 'SPD Smith': 198,
 'AD Russell': 21,
 'AR Patel': 31,
 'KA Pollard': 137,
 'HH Pandya': 96,
 'JC Buttler': 85,
 'P Negi': 202,
 'DJ Hooda': 72,
 'MJ Guptill': 125,
 'SW Billings': 206,
 'KS Williamson': 148,
 'MP Stoinis': 182,
 'RR Pant': 171,
 'UT Khawaja': 219,
 'HM Amla': 76,
 'SA Yadav': 254,
 'Shakib Al Hasan': 282,
 'N Rana': 192,
 'KH Pandya': 140,
 'PP Chawla': 210,
 'C Munro': 37,
 'ER Dwivedi': 65,
 'JJ Roy': 89,
 'Vishnu Vinod': 225,
 'RA Tripathi': 165,
 'BA Stokes': 46,
 'SP Narine': 274,
 'TM Head': 217,
 'Ishan Kishan': 80,
 'SP Jackson': 196,
 'R Tewatia': 224,
 'C de Grandhomme': 55,
 'MM Ali': 178,
 'JM Bairstow': 91,
 'PP Shaw': 155,
 'NS Naik': 145,
 'SM Curran': 269,
 'SN Khan': 193,
 'V Shankar': 222,
 'Shubman Gill': 211,
 'JL Denly': 90,
 'E Lewis': 63,
 'DJM Short': 58,
 'AD Hales': 10,
 'K Gowtham': 132,
 'JC Archer': 112,
 'BCJ Cutting': 49,
 'AD Nath': 12,
 'P Kumar': 201,
 'Z Khan': 317,
 'AA Noffke': 13,
 'B Lee': 43,
 'S Sreesanth': 251,
 'GD McGrath': 89,
 'B Geeves': 40,
 'MF Maharoof': 172,
 'AB Dinda': 15,
 'I Sharma': 100,
 'AB Agarkar': 14,
 'M Kartik': 162,
 'R Vinay Kumar': 225,
 'MM Patel': 179,
 'SK Trivedi': 265,
 'SK Warne': 266,
 'Mohammad Asif': 185,
 'A Nehra': 6,
 'DS Kulkarni': 83,
 'Pankaj Singh': 213,
 'JDP Oram': 115,
 'MS Gony': 184,
 'P Amarnath': 199,
 'M Muralitharan': 165,
 'Sohail Tanvir': 286,
 'RP Singh': 232,
 'DNT Zoysa': 79,
 'SB Bangar': 255,
 'VRV Singh': 304,
 'DW Steyn': 85,
 'CRD Fernando': 64,
 'Umar Gul': 299,
 'VY Mahesh': 307,
 'PJ Sangwan': 208,
 'DP Vijaykumar': 81,
 'Gagandeep Singh': 93,
 'A Kumble': 3,
 'WPUJC Vaas': 309,
 'AD Mascarenhas': 19,
 'PM Sarvesh Kumar': 209,
 'RR Powar': 234,
 'M Ntini': 166,
 'VS Yeligati': 306,
 'BAW Mendis': 47,
 'Kamran Khan': 151,
 'T Thushara': 291,
 'A Flintoff': 2,
 'DP Nannes': 80,
 'AM Salvi': 28,
 'DL Vettori': 78,
 'FH Edwards': 86,
 'Harmeet Singh': 99,
 'PP Ojha': 211,
 'L Balaji': 155,
 'Joginder Sharma': 130,
 'Anureet Singh': 36,
 'RR Bose': 233,
 'YA Abdulla': 313,
 'SL Malinga': 267,
 'VS Malik': 305,
 'SM Harwood': 270,
 'D du Preez': 67,
 'RJ Harris': 230,
 'Shoaib Ahmed': 285,
 'A Singh': 7,
 'M Morkel': 164,
 'LA Carseldine': 157,
 'S Tyagi': 252,
 'A Mithun': 5,
 'RR Raje': 235,
 'B Akhil': 39,
 'CK Langeveldt': 61,
 'Jaskaran Singh': 129,
 'SW Tait': 279,
 'A Uniyal': 9,
 'R Ashwin': 215,
 'SE Bond': 262,
 'S Ladda': 247,
 'JM Kemp': 122,
 'SJ Srivastava': 263,
 'Bipul Sharma': 54,
 'J Theron': 109,
 'S Narwal': 250,
 'KAJ Roach': 138,
 'SB Jakati': 256,
 'AC Voges': 18,
 'SB Wagh': 258,
 'AN Ahmed': 29,
 'AP Dole': 30,
 'MR Marsh': 183,
 'L Ablish': 154,
 'DE Bollinger': 69,
 'UT Yadav': 298,
 'JD Unadkat': 114,
 'Iqbal Abdulla': 105,
 'AC Thomas': 17,
 'AG Murtaza': 23,
 'JJ van der Wath': 121,
 'S Aravind': 241,
 'RV Gomez': 237,
 'R Ninan': 219,
 'J Syed Mohammad': 108,
 'NL McCullum': 195,
 'JE Taylor': 117,
 'R Sharma': 222,
 'KMDN Kulasekara': 145,
 'TG Southee': 293,
 'BA Bhatt': 45,
 'P Parameswaran': 203,
 'S Nadeem': 249,
 'B Kumar': 41,
 'VR Aaron': 303,
 'AA Chavan': 11,
 'SS Mundhe': 277,
 'RW Price': 238,
 'DAJ Bracewell': 68,
 'HV Patel': 97,
 'GB Hogg': 87,
 'P Awana': 200,
 'A Chandila': 0,
 'RJ Peterson': 231,
 'CJ McKay': 60,
 'R Shukla': 223,
 'KP Appanna': 146,
 'V Pratap Singh': 301,
 'BW Hilfenhaus': 52,
 'K Upadhyay': 136,
 'Sunny Gupta': 287,
 'MG Johnson': 173,
 'JJ Bumrah': 120,
 'AS Rajpoot': 33,
 'Mohammed Shami': 188,
 'CH Morris': 57,
 'Anand Rajan': 34,
 'MM Sharma': 180,
 'SMSM Senanayake': 272,
 'R Rampaul': 221,
 'R Dhawan': 217,
 'JO Holder': 123,
 'IC Pandey': 101,
 'KW Richardson': 150,
 'MG Neser': 174,
 'PV Tambe': 212,
 'Parvez Rasool': 214,
 'S Kaul': 245,
 'Sandeep Sharma': 280,
 'NM Coulter-Nile': 197,
 'MA Starc': 170,
 'JDS Neesham': 116,
 'YS Chahal': 315,
 'S Badree': 242,
 'Shivam Sharma': 284,
 'Imran Tahir': 104,
 'BE Hendricks': 50,
 'PJ Cummins': 207,
 'K Santokie': 135,
 'S Gopal': 244,
 'Karanveer Singh': 152,
 'D Wiese': 66,
 'MJ McClenaghan': 176,
 'DJ Muthuswami': 74,
 'SA Abbott': 253,
 'TA Boult': 292,
 'P Suyal': 206,
 'RG More': 228,
 'GS Sandhu': 92,
 'J Suchith': 107,
 'M de Lange': 169,
 'J Yadav': 110,
 'JW Hastings': 128,
 'Mustafizur Rahman': 191,
 'CR Brathwaite': 62,
 'KJ Abbott': 141,
 'P Sahu': 205,
 'BB Sran': 48,
 'T Shamsi': 290,
 'Swapnil Singh': 288,
 'SM Boland': 268,
 'CJ Jordan': 59,
 'S Kaushik': 246,
 'DL Chahar': 77,
 'KC Cariappa': 139,
 'TS Mills': 297,
 'A Choudhary': 1,
 'CR Woakes': 63,
 'Kuldeep Yadav': 153,
 'T Natarajan': 289,
 'Rashid Khan': 239,
 'Basil Thampi': 53,
 'AJ Tye': 25,
 'AF Milne': 22,
 'K Rabada': 134,
 'Washington Sundar': 310,
 'SN Thakur': 273,
 'SS Agarwal': 276,
 'NB Singh': 194,
 'Mohammad Nabi': 187,
 'Mohammed Siraj': 189,
 'A Zampa': 10,
 'LH Ferguson': 159,
 'M Prasidh Krishna': 167,
 'Rasikh Salam': 240,
 'CV Varun': 65,
 'GC Viljoen': 88,
 'NA Saini': 193,
 'M Ashwin': 161,
 'S Lamichhane': 248,
 'P Ray Barman': 204,
 'Avesh Khan': 37,
 'Mujeeb Ur Rahman': 190,
 'SC Kuggeleijn': 260,
 'JP Behrendorff': 124,
 'AS Joseph': 32,
 'MJ Santner': 177,
 'KMA Paul': 144,
 'KK Ahmed': 142,
 'IS Sodhi': 103,
 'B Stanlake': 44,
 'K Khejroliya': 133,
 'Shivam Mavi': 283,
 'B Laughlin': 42,
 'LE Plunkett': 158,
 'M Markande': 163,
 'DJ Willey': 75,
 'L Ngidi': 156,
 'TK Curran': 294,
 'HF Gurney': 95,
 'R Parag': 220,
 'O Thomas': 198}

In [ ]:
ip_dataset.drop('non_striker',axis=1,inplace=True)

<ipython-input-133-825b5bbf1c3c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ip_dataset.drop('non_striker',axis=1,inplace=True)

In [ ]:
X= ip_dataset.iloc[:,]
y = dataset.y

In [ ]:
dataset = dataset.drop('y',axis = 1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

In [ ]:
X_test.shape

(9654, 6)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression
lin = LinearRegression()
lin.fit(X,y)

LinearRegression()

In [ ]:
from sklearn.ensemble import RandomForestRegressor
lin = RandomForestRegressor(n_estimators=100,max_features=None)
model =lin.fit(X_train,y_train)

In [ ]:
model

RandomForestRegressor(max_features=None)

In [ ]:
y_pred = lin.predict(X_test)
score = lin.score(X_test,y_test)*100
print("Score value:" , score)
# Larger score value indicates a better fit

Score value: 93.5350794264373

In [ ]:
def prediction(d):
    lst = pd.read_csv(d)
    lst['bowlers'] = lst[lst.columns[5:]].apply(lambda x: ','.join(x.dropna().astype(str)),axis=1)
    #lst.drop(['Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],axis = 1,inplace=True)
    labeled_data=[]
    for i in lst:
        val = lst[i][0]
        if type(val)==str:
            if val in features.keys():
                labeled_data.append(features[val])
        else:
            labeled_data.append(val)
    bowl = lst['bowlers'][0].split(',')
    for i in bowl:
        labeled_data.append(features[i])
    l1 = labeled_data[:6]
    l2 = labeled_data[:5]
    l2.append(labeled_data[6])
    l3 = labeled_data[:5]
  #  l3.append(labeled_data[7])
  #  l4 = labeled_data[:5]
  #  l4.append(labeled_data[8])
  #  l5 = labeled_data[:5]
  #  l5.append(labeled_data[9])
    l1 = np.array(l1).reshape(1,6)
    y_pred = lin.predict(l1)
    print(y_pred)

In [ ]:
#print(features.values())

**Save the model**

In [ ]:
import pickle

In [ ]:
with open('model.bin', 'wb') as f_out:
    pickle.dump(lin, f_out)
    f_out.close()

In [ ]:
with open('model.bin','rb') as f_in:
    model = pickle.load(f_in)

In [ ]:
prediction('/content/drive/MyDrive/Wids_IPL_Analysis_Data/inputFile.csv')
#temp = pd.read_csv('/content/drive/MyDrive/Wids_IPL_Analysis_Data/inputFile.csv')
#temp.head()

[45.89]